### ISSUE TITLE
kcorr_data path goes wrong when built

### ISSUE THREAD

**Issue by bertiepwhite** [RobFirth/pycoco#20]
when runnning from egg rather than just having module in the path, the `default_kcorr_dir` goes to `/Users/bertiepwhite/.local/lib/python3.6/site-packages/pycoco-0.7.0-py3.6.egg/pycoco/kcorr_data`
Solution to this is to have a data directory and manifest set up in the `setup.py`

**Comment by RobFirth** [comment]
This has been fixed by properly passing `package_data={"pycoco":['kcorr_data/*']}` to `setup` in `setup.py`
