### ISSUE TITLE
pcc.utils.get_notebooks() crash

### ISSUE THREAD

**Issue by msullivan318** [RobFirth/pycoco#36]
pcc.utils.get_notebooks() crashes for me. I think you need to change line 609 of utils.py:

        tar = tarball.open(tarball, "r:gz")
to
        tar = tarfile.open(tarball, "r:gz")

or at least that worked for me.

**Comment by RobFirth** [comment]
yep - tarfile is the imported module, tarball is the file path. I've made the suggested change and pushed. It will be in the next pip release
